global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    basic_auth:
      username: 'admin'
      password: 'teste'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']